### ISSUE TITLE
Not working on 5.0.4

### ISSUE THREAD

**Issue by rdemendoza** [fraoustin/redmine_default_due#1]
Hi,
It seams that defaultdue.js is not loaded.
I don't see console.log("defaultDue"); on the browser console.

**Comment by fraoustin** [comment]
Hi

I test the plugin with redmine 5.0.4 and docker

My Dockerfile

> FROM redmine:5.0.4
> WORKDIR /usr/src/redmine/plugins
> RUN git clone https://github.com/fraoustin/redmine_default_due.git
> WORKDIR /usr/src/redmine/


I build and run my image


> docker nuild -t test .
> docker run --name test -p 3000:3000 test


I connect to 127.0.0.1:3000

I have a redmine with version 5.0.4

![image](https://user-images.githubusercontent.com/3457495/218300986-1ffaad6b-16e4-41f5-ac80-eaebdd9e867d.png)

the plugin is active

![image](https://user-images.githubusercontent.com/3457495/218301125-0538c8f6-5f83-4f5f-8878-d57720a6bd3b.png)

And when create a new demand, I see on console.log

![image](https://user-images.githubusercontent.com/3457495/218301152-6cee21e8-1b7e-4ba5-b66c-9c1bc23d8ce1.png)

For me all is ok

Have you the plugin in the plugin administration?

Do you use docker ?

Where you have copied the files of the plugins?

We are going to found a solution ;-)

**Comment by rdemendoza** [comment]
Hi,
We don't use docker, we are on a self-hosted Ubuntu 22.04.

Here is my configuration:
<img width="590" alt="infos" src="https://user-images.githubusercontent.com/11791031/218346435-2c3df409-14fd-4ba9-ab95-eaa32a6ab918.png">

The files are in: plugins/redmine_default_due

The plugin is active:
<img width="1021" alt="Capture d’écran 2023-02-13 à 01 26 28" src="https://user-images.githubusercontent.com/11791031/218346503-fd48608e-256a-431b-8e04-d91d55214f31.png">

I don't see the defaultdue.js loaded in the network tab:
<img width="586" alt="Capture d’écran 2023-02-13 à 01 27 43" src="https://user-images.githubusercontent.com/11791031/218346574-1e974ef2-ca44-4873-a172-6af8d47d7714.png">

I have no error in the logs...

Thanks in advance :)

**Comment by rdemendoza** [comment]
After doing theses commands it works :)

```
bundle exec rake deface:precompile RAILS_ENV=production
bundle exec rake deface:clean RAILS_ENV=production
```

**Comment by fraoustin** [comment]
I change the README
